### PR TITLE
Show boolean parameter issues in PitHub::Repos::Releases

### PR DESCRIPTION
**Pull request by timlegge**
@oalders Based on the quick review of the live test this might do what you want...

Tests #231

### CODE REVIEW

**Comment by oalders** [comment]
Thanks, @timlegge! Am closing and re-opening to kick off a CI build.

**Comment by oalders** [comment]
@timlegge I don't think that test is failing here. Possibly related to whatever `JSON::MaybeXS` is using under the hood in your case?

**Comment by timlegge** [comment]
Thought about it after.  My test assumes it will fail and does not raise the error.  I will sort tonight and see if that makes any difference

**Comment by timlegge** [comment]
@oalders can you bounce again to trigger the workflow?

**Comment by timlegge** [comment]
Well that is odd.  The live test does call the github API for real correct?

I will look at my install...

**Comment by oalders** [comment]
Ah, the CI tests don't set `PITHUB_TEST_LIVE_DATA` or `PITHUB_TEST_TOKEN`, so as it currently stands these tests won't get run. 🤔 

Is there any endpoint that uses true/false which doesn't need to create anything? We could at least take `PITHUB_TEST_TOKEN` out of the mix in that case.

**Comment by timlegge** [comment]
The only place seems to be in an unimplemented call to Orgs/rulesets. 

When/ If you have time to reproduce 
Dist::Zilla::Plugin::GitHub::CreateRelease shows the issue (https://github.com/timlegge/perl-Dist-Zilla-Plugin-GitHub-CreateRelease).  I can give you permissions to https://github.com/timlegge/perl-Acme-TIMLEGGE-Test-This where I test making a release simply with:

`dzil build; git add Changes Makefile.PL README; git commit -m "Yet another release"; dzil clean; sed -i 's/NEXT}}/NEXT}}\n\n    - Yet another release/' Changes;  dzil release`

Based on what I read in the code it seems like the arguments are simply passed to json->encode

according to https://metacpan.org/pod/Cpanel::JSON::XS#$json_text-=-$json-%3Eencode-($perl_scalar,-$json_type)

Neither true nor false values will be generated.

**Comment by oalders** [comment]
Out of curiosity, have you tried `JSON::PP::true` and `JSON::PP::false` for passing boolean values?

**Comment by timlegge** [comment]
@oalders  if I change it to require JSON::PP and use $JSON::PP::true and $JSON::PP::false it does work.

```
diff --git a/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm b/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm
index abbd62c..85d507c 100644
--- a/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm
+++ b/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm
@@ -30,9 +30,6 @@ has notes_file => (is => 'ro', default => 'Release-VERSION');
 has draft => (is => 'ro', default => 0);
 has add_checksum => (is => 'ro', default => 1);
 
-use constant false => \0;
-sub true () { return \1 } # note the empty prototype
-
 sub _create_release {
   my $self      = shift;
   my $tag       = shift;
@@ -53,15 +50,16 @@ sub _create_release {
   );
   die "Unable to instantiate Pithub::Repos::Releases" if (! defined $releases);
 
+  require JSON::PP;
   my $release = $releases->create(
     data => {
       tag_name         => "$tag",
       target_commitish => $branch,
       name             => $title,
       body             => $notes,
-      draft            => $self->{draft} ? true : false,
-      prerelease       => $self->zilla->is_trial ? true : false,
-      generate_release_notes => $self->{github_notes} ? true : false,
+      draft            => $self->{draft} ? $JSON::PP::true : $JSON::PP::false,
+      prerelease       => $self->zilla->is_trial ? $JSON::PP::true : $JSON::PP::false,
+      generate_release_notes => $self->{github_notes} ? $JSON::PP::true : $JSON::PP::false,
     }
   );
   die "Unable to create GitHub release\n" if (! defined $release->content->{id});

```

**Comment by oalders** [comment]
Excellent! I'm guessing the same would hold true for `Cpanel::JSON::XS::true` and `Cpanel::JSON::XS::false`? If we could update the docs, I think that would helpful.

**Comment by timlegge** [comment]
And this

```
diff --git a/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm b/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm
index abbd62c..6b917aa 100644
--- a/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm
+++ b/lib/Dist/Zilla/Plugin/GitHub/CreateRelease.pm
@@ -30,9 +30,6 @@ has notes_file => (is => 'ro', default => 'Release-VERSION');
 has draft => (is => 'ro', default => 0);
 has add_checksum => (is => 'ro', default => 1);
 
-use constant false => \0;
-sub true () { return \1 } # note the empty prototype
-
 sub _create_release {
   my $self      = shift;
   my $tag       = shift;
@@ -53,15 +50,16 @@ sub _create_release {
   );
   die "Unable to instantiate Pithub::Repos::Releases" if (! defined $releases);
 
+  require JSON::MaybeXS;
   my $release = $releases->create(
     data => {
       tag_name         => "$tag",
       target_commitish => $branch,
       name             => $title,
       body             => $notes,
-      draft            => $self->{draft} ? true : false,
-      prerelease       => $self->zilla->is_trial ? true : false,
-      generate_release_notes => $self->{github_notes} ? true : false,
+      draft            => $self->{draft} ? JSON::MaybeXS::true : JSON::MaybeXS::false,
+      prerelease       => $self->zilla->is_trial ? JSON::MaybeXS::true : JSON::MaybeXS::false,
+      generate_release_notes => $self->{github_notes} ? JSON::MaybeXS::true : JSON::MaybeXS::false,
     }
   );
   die "Unable to create GitHub release\n" if (! defined $release->content->{id});

```

**Comment by timlegge** [comment]
I am thinking something like this as well as a possible mention on the main module page that if the api calls for a boolean see the Repos/Releases documentation:

```
diff --git a/lib/Pithub/Repos/Releases.pm b/lib/Pithub/Repos/Releases.pm
index 10afd8e..9055492 100644
--- a/lib/Pithub/Repos/Releases.pm
+++ b/lib/Pithub/Repos/Releases.pm
@@ -110,11 +110,57 @@ Examples:
             target_commitish => 'master',
             name             => 'v1.0.0',
             body             => 'Description of the release',
-            draft            => 0,
-            prerelease       => 0,
+            draft            => JSON::MaybeXS::false,           # or alternative below
+            prerelease       => JSON::MaybeXS::false,           # or alternative below
+            generate_release_notes => JSON::MaybeXS::false,     # or alternative below
         }
     );
 
+Booleans:
+
+Several of the attributes B<require> boolean values in the request that is sent
+to GitHub.  Zero (0) and one (1) are integers and will not be encoded correctly
+in the JSON encoded request.
+
+There are numerous options for your call to Pithub::Repos::Releases->create.
+
+=over
+
+=item JSON::MaybeXS
+
+Add the following to your code before the call to Pithub::Repos::Releases->create.
+
+    require JSON::MaybeXS;
+
+Then use the following values for the booleans:
+
+    JSON::MaybeXS::true
+    JSON::MaybeXS::false
+
+=item Cpanel::JSON::XS
+
+Add the following to your code before the call to Pithub::Repos::Releases->create.
+
+    require Cpanel::JSON::XS;
+
+Then use the following values for the booleans:
+
+    Cpanel::JSON::XS::true
+    Cpanel::JSON::XS::false
+
+=item JSON::PP
+
+Add the following to your code before the call to Pithub::Repos::Releases->create.
+
+    require JSON::PP;
+
+Then use the following values for the booleans:
+
+    $JSON::PP::true
+    $JSON::PP::false
+
+=back
+
 =back
 
 =cut

```

**Comment by timlegge** [comment]
@oalders you can close the PR and use #233

**Comment by oalders** [comment]
Thanks @timlegge!

**Pull request closed without merging**
